credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin User
      password: abc123

cookie:
  expiry_days: 30
  key: ai_cv_analyzer_signature
  name: ai_cv_analyzer_cookie