credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Ayoub User
      password: ayoub2005

cookie:
  expiry_days: 30
  key: ai_cv_analyzer_signature
  name: ai_cv_analyzer_cookie