credentials:
  usernames:

    admin:
      email: admin@example.com
      name: Admin User
      password: abc123

    ayoub:
      email: ayoublouraoui@gmail.com
      name: Ayoub
      password: ayoub2005

    fati:
      email: fatimazahralouraoui@gmail.com
      name: Fati
      password: fati2001

cookie:
  expiry_days: 30
  key: ai_cv_analyzer_signature
  name: ai_cv_analyzer_cookie